name: first workflow

on: push

jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:

            - name: clone repo inside runner
              uses: actions/checkout@v6
            - name: welcome message
              run: echo "Welcome to github actions"

            - name: list all files
              run: ls -la
 
            - name: multi-line command usage
              run : | 
                date
                echo "Today's date is $(date)"
                cat README.md
                echo "multi line command needs pipe symbol"
              

