name: ASCII artwork

on: push 

jobs:
    art-job:
        runs-on: ubuntu-latest
        steps:
            
            - name: ASCII artwork
              run: | 
                sudo apt-get install cowsay -y
                cowsay -f dragon "I am mother of dragons" >> dragon.txt

            - name: artwork file check
              run: grep -i "dragon" dragon.txt

            - name: ASCII artwork output
              run: cat dragon.txt