name: multi-job-pipeline-1

on: push 

jobs:
    art-job:
        runs-on: ubuntu-latest
        steps:
          - name: ascii-art-job
            run: | 
               sudo apt-get install cowsay -y
               cowsay -f dog "dogs are our best friend" >> dog.txt

          - name: check art job generation
            run : | 
              grep -i "dogs" dog.txt

          - name: print the art
            run: cat dog.txt

    script-job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo code
              run: actions/checkout@v6
            
            - name: executing test script
              run: | 
                chmod +x test.sh
                ./test.sh

            - name: script-job-check
              run: echo "script-job executed successfully"
